language: java
jdk:
- oraclejdk8
sudo: false
before_install:
- cp ./settings.xml ~/.m2/
script:
- mvn -B clean verify
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]] &&
  { mvn -B clean deploy -DskipTests; };'
after_script:
- mvn clean -DsourceEncoding=UTF-8 cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
    on_success: always
env:
  global:
  - secure: rxLPX75PH3dawZyRE7Pv5AqGlZ578aiyBTUULQiubT03WtQZjLxGZYrwz3mrxo3tdYU3z+nsMLxiCTtkTjfUuhA2DlqdbY0Z/6X26jJ3dTX2JMJpq+VwYuF9QayvpvIx8pOzTijqpWy9Rqzseod62fckHy6vy6Ld5V6vh/L2Yvumsg/UT4KQmBsCENJU4FILyyQtMvFgpYvh3tpnupR2f0X3N/L3yxdtjOdUdOMNQ1ZZtRjM9iVf/8qPYtWGCeFvq2aXFPYWE068MYOOZYC5zVBa8AdA2htUDr30La3MEAk3WG/d7GpRAhDB4fhq/oFdqwiN5AJyNwJfukY5CqnsvYheEaXcyzpulRpSHEAVae5+SV6iUv9BHThyw8S17z+gEYThtxmfY/CQf5P18nBvsv1K/TvxLPmrd2lUvkmVZYNnPPZSJg+BqJxt4P1RnKTMtGTwQ1zz/I/4RXCNdvmdw04ZVfLXp1LcQBW5JWVSpgG55x2/wrqHa6F/oMclmDexVnmcfhZForW0HK0tjJhReddYStMPaHWaBdVMVWkE7awXvXRQXrCjgYIoScAOU/SvSMZmsLdl1UozHHZgwTBXFZySTkAIQQ7+k73cahNIFfnzqoX/Fq7BefO4yCK75/HgbkgPb60ZCfYDINlnEYQGdIXMa4CO+z7omcizVwBX0qc=
  - secure: nM/yB+rJ1pPAuSYw/yL1685TW2z/TbmVWZQYwgP979skJ7A5XN862I5sKQTiHZbCLisHUwAvFJdO73ZbdPMcJzl7eRihVDvaFakHHFCmdXlsJwAKNyDTmzMp0prUKdvoqTIpwkBpFXEyJKZedr/mcEX06XKiEFUyqhDFAnABHEs4qvRBByi6L3eZk5uB6M4vuEUhetOyPn4cEH3RPoOgQSMihbcBL2fz79vih8JgKd7sequ94RUVniVUpKgOUL63fjcJXKsrropcqtMJZM8wF2N3+zyQY109kOIUglgPQNzsZUTQH1OQdo6B2kk+6+pUZhtz6SQWvgak26VYfOQqNGSdLvaD7/k4FUNEz+tX3lRM6Tavc2VdeQj+X1eEuP6S+Y/RJH2Qqh9jwvx6Zi/tJLi5d2H6/nQd66wEheVQOk7ICUvgkyEwCzzwicoWLYID5qAZVBu+87UWzbot1LC67Hn9dZdi9nj+0IJ9qLMXvc825sr85u2n3OXtq+dLBBE/SRHLEVchypm/xcwoX0cl2R+nG/46EDEBEK3YqDDoUVJy+1mkl2ps6KrBQrKL0Pvj7I97f0mOQ6dOFQTJXAMhtn4D7qRidA5ghRPZMK8Q+Fm0/V3BSOJd6McYRaeLwwtq/TfdB6fybx8Mm0Mcu47XYMDgUJHTmCyoLddmP8KbhFE=
