language: java
jdk:
  - oraclejdk8
sudo: false
before_install:
  - cp ./etc/settings.xml ~/.m2/
  - cp ./etc/onTravisBuildFailure.sh  ~/
  - cp ./etc/onTravisBuildSuccess.sh  ~/
  - chmod 777 ~/onTravisBuildFailure.sh
  - chmod 777 ~/onTravisBuildSuccess.sh
script:
  - mvn -B clean verify
after_failure: "~/onTravisBuildFailure.sh"
after_success: "~/onTravisBuildSuccess.sh"
after_script:
  - mvn clean -DsourceEncoding=UTF-8 cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
    on_success: always
env:
  global:
  - secure: Xi7rM/qY/kjW6WxMTgme6a8KxjtDwqTWhERo/srIPoEpQiOFLhLrB0e6Wl4KaNKukz1jOw4GQ9A4s8dt7sDmF5Ty6wbWvMToE5KsDySNNggVn074evrZaG34YaQKJKNBYqu6tBXO0B5LRWWoNNIUTRjAMVj5Q1R5Ddq5yVrRRZ2L22OmzRICaJ5kvt1Of68Rr8x4U1aFW4rb52RgOL4mtOKmL9R9rU3ZsA4sF1gk0dGCaSGX5nvDkHL9jjCuUUPMJSBNJ8gS6z70TzCFOmWGUYPYwq9t3J+wGmcfWlbdPxlu9noLri1PMsJrhiiY0aO7jgpSbqMA4/ztiiQLSaMFTUfs2IU/8AQlJryeBAXszAjs3f+MFbXgoR3G/WU/xLMulVQ06gEoMFDGvaqMV69CBMn0eoWfcDbewjq3fpXv72SAVFOcZV05bEWG6UBZWSG0DseVgzgpQdbia6QLPmtggArMImHO2kkEuXBNs7EMXjh0LXeKkZNLbhLQrvkYbCDay6sZrJStUIdhj0hiPKHOVWlr9eqyuebwRJpjpG6lhjruUuute2NYYKRBK6gdZsgFir6H9BfOao+jD4udgNew8M5V38mvloJ92qH6F/1D0Iw6E/tQXpDKR10oWqTzU10oFJVDXikl7FM6NAxCTA9WOIqCRwa90qlat/l51Cxqmjk=
  - secure: LezM3jKP+xGoJ4Y70zOgnt1U8xwlU0zXYjDz5GPH3f6VB/OGeojhHUvNk+xgwra99Jn8xiG93tbevgBTdbwQnKM3Zkwz9C0+PRe9wHvoDvRXbsC1ZbV9ZDMDsSwrrY5cty1Goao/rSL9W3oIXb0Ao1VDVxdEd27nXlRfeFpfH4KmRROGNxieu/ggmeI6P4a/GT6cB8o6IybX+DBvdVU88+Holi6fJqBYh4OOEdHNdRA8z93Tb8YOw23SEYeKkdiY8vzKx40NODNccGSVVSRKutJi1uxufZm/p5uQHqw1Q77hN8kHfx2r45bJdNWAUDQ+9iFdS5G43uB6ABcjrIL3IXUAblNW54vknryjJEYBcGYGpiWoMB2+CsiPNOKdW/Hy2j7pzlOVMYA/DaMSNIAnvUNrrELTghf1MhuA5qfwL//fEEfJQOJKG7w9U5Ga1G73TVkpy8gEXFmiTD8zAUtXABnLUJWTH+tzxdMfcw+xq7jiNNx15hwaKGM5AYdwlKlr7t7SGWpkhzFQ+Az2BzcjZegShUjE6Ub/+f+fykB8Uk9zr68iknN3X8jOAtTKlShS8IVgCzRtlJ105RulrYpsfjvVNqPm6BNF05W6eET0qwy3yQw3jeZPr9KdCmKbk0Rdi70/a5Og0k98KDszIwhhj4TE9Qv+otNrBL2UveQkivE=
