language: java
jdk:
- oraclejdk8
sudo: false
before_install:
- cp ./settings.xml ~/.m2/
script:
- mvn -B clean verify
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]] &&
  { mvn -B clean deploy -DskipTests; };'
after_script:
- mvn clean -DsourceEncoding=UTF-8 cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
    on_success: always
