language: java
jdk:
- oraclejdk8
sudo: false
before_install:
- cp ./settings.xml ~/.m2/
script:
- mvn -B clean verify
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_JDK_VERSION == "oraclejdk8" ]] &&
  { mvn -B clean deploy -DskipTests; };'
after_script:
- mvn clean -DsourceEncoding=UTF-8 cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
    on_success: always
env:
  global:
  - secure: GOvHsPH3eb7TNYogkVfoAEKSDJ+VGTKJBCoPNXPV6JR1UgPeEUSUZvh5cyy2mLpUCP8gv70irrLvThhGgHbVCh4ReAIA01LQSDGatN57Wlb0j6ZJO2+dvw+yXSiSXNoZ+AaFtNUga/vLhWRWdN6+ayiSYxFjmLLo8PTyMxtqSDXDd6IcxIdnEuVyZtb3tCQgMEHMmKMKK0jhv3BybmCMWQM2QtOwsQv7L9s++SHTN/LYN8Jub9t/6EhFdL0BRjSKjp6GjZnBWPI7OQGagMg/znF/21wtD0LaJ2T9SMKZMnFk9yRiWTkfqZe1RmHz9BYKiW61+KXxZYCphGMMym9FzqjmbUgaR8AmSoNX+gvJi0dbMxXqU/rGM6Kad96WhY5ctuJ0IX7od/W0hnMJFhX+l/TB+XJbCt9d6arNmsJbtihkOfbhX0mzNYMl8g3c68c944rRRL+pEeX+yFO/JO/I5OLv/LcgObpciPCjUOwW89tQmbNTmjVfq2uEuBxRes9dhvEL7IjJOPC2Zh42LNRmEi3b3YvX7/CKBc/IlXHShVz7/l5TNYseWJZBauYP/KEfJFXlFcf00TxdfB0mwEx1D4H06htGm8GXei3A3zbXkY/ZhqexdmWfcYsw5fGULOCdvmcCDAz0nO59+Vvy/ucSm8wsgFfyUnB2u/5bsj3sKuc=
  - secure: JvzhpgFQ6IWUhkEJngHXSGelmPmlXjlCGUyrTFP/Ukv8+xByhfMsLblYmXWsKyX0PhcVApui/QJUyERp3dx/dTtOPE89ZGMEmZf9Q05uoKtka6SmmwS92hLJXTGVVf4D82emskw3m7sH/UkzSYAmVApqHjL5yAAyTc9f5s3T1ZVjmq1Ug/x+70MkYQougCDIQNcc51GbLD+moGvJi3hbWoy+Wm5GSgQSLfHRlAZSmaM+/FGuHGyO0S525281xmitsbbpAs0HQZt8yW5d3uV/SgJoUXvTx7+3DKI91JClFhUKb70VCBwIJ6DQeVAgFb5bjgJB1YRo96v4/NrtJqQdmfFeizG9kY2kx7MFs4pPRGazqtnrnLsrwKug3pjiFVsdSwM8Lw9wcni98mdnu+i0DKI/Z07mmHkji/2nxWktUFHSo+n1HaNFTrgHBXvRsPGUvrw90B1jT4oh6zX7Z0zX3ls5kROJjtV1CuoimwQRJIXBsxABf73luLg4YcZuuswpOBIfkt51ZGqzBX7VBgsjAEhCp7OlEhvOzP2VJhnPYeoUZM/9qt+vmeTsUuSDVgjwaoNkd330Z0jIgKPn7NYjc5tE3J1UJq8q+3BwjEALTEYiROE3wnWkrlOwOo3XOY+Tw281jOMwsDIogHwcSJ+gMsVu50bv5CBAdw3f420tj8M=
